const actions = {
  SET_STATE: 'storage/SET_STATE',
  GET_FRESH_ITEM_STOCK: 'storage/GET_FRESH_ITEM_STOCK',
  GET_FROZEN_ITEM_STOCK: 'storage/GET_FROZEN_ITEM_STOCK',
  GENERATE_DELIVERY_ID: 'storage/GENERATE_DELIVERY_ID',
  GET_PENDING_TRANSACTION: 'storage/GET_PENDING_TRANSACTION',
  DELIVER_ITEM: 'storage/DELIVER_ITEM',
  GENERATE_CONVERSION_ID: 'storage/GENERATE_CONVERSION_ID',
  PROCESS_ITEM_CONVERSION: 'storage/PROCESS_ITEM_CONVERSION',
}

export default actions
